redas:
  mq:
    host: 192.168.2.2:9092
    group: test
    topic: test
  elasticsearch:
    recr_page:
      scheme: http
      host: 192.168.0.4
      port: 9200
      index: redas
      type: recr_page